package by.epamtc.birukov.controller.command;

public enum ParameterName {
    CREATE_NEW_USER,
    AUTHORIZATION,
    GREETING,
    GO_TO_LOGIN,
    GO_TO_REGISTRATION,
    CHANGE_LANGUAGE,
    GO_TO_SETTINGS,
    GO_TO_CREATE_TEST,
    CREATE_TEST,
    CREATE_QUESTION,
    SHOW_ALL_TESTS,
    SHOW_TEST_BY_NAME,
    SHOW_ALL_USERS,
    GO_TO_APPOINT_TEST,
    APPOINT_TEST,
    VIEW_ASSIGNED_TESTS,
    PASS_TEST,
    LOGOUT,
    GO_TO_HALLO_PAGE,
    SEND_ANSWERS
}
